#
# General Settings
#
wp_box: pjsweb/xenial64

#
# Network Settings
#
hostname: wordpress.devel 
ip: 192.168.33.10

#
# WordPress Settings
#
version: latest
lang: en_GB
title: Welcome to WPBox 
multisite: false
rewrite_structure: /archives/%post_id%

#
# WordPress Options
#
options:
  blogdescription: WordPress in Vagrant.

#
# WordPress Path
#
wp_siteurl: ''  # Path to the WP_SITEURL like "wp"
wp_home: ''     # Path to the WP_HOME like "wp"

#
# WordPress User
#
admin_user: admin
admin_pass: admin
admin_email: wordpress@example.com

#
# WordPress Database
#
db_prefix: wp_
db_host: localhost
db_name: wordpress
db_user: wordpress
db_pass: wordpress

#
# WordPress Default Plugins to remove
# Plugin's slug or url to the plugin's slug.
#
rmplugins:
- hello

#
# WordPress Default Plugins
# Plugin's slug or url to the plugin's slug.
#
plugins:
- logbook
- password-protected
- wordpress-importer

#
# WordPress Default Theme
# Theme's slug or url to the theme's .zip.
#
theme: ''


#
# WordPress Multisite Options
#
multisite_options: {}

#
# The values of wp-config.php
#
force_ssl_admin: false
wp_debug: true
savequeries: false

gitignore: https://raw.githubusercontent.com/github/gitignore/master/WordPress.gitignore

#
# Addtional PHP code in the wp-config.php
#
extra_wp_config: |
  define('WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . '/wp-content');
  define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . '/wp-content');

